version: '3'
services:

  mosquitto:
    container_name: mosquitto
    image: "eclipse-mosquitto:latest"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./volumes/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./volumes/mosquitto/data:/mosquitto/data
      - ./volumes/mosquitto/password_file:/mosquitto/pwd

  homeassistant:
    container_name: homeassistant
    image: "homeassistant/home-assistant:latest"
    ports:
      - "8123:8123"
    volumes:
      - ./volumes/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always

  esphome:
    container_name: esphome
    image: "esphome/esphome"
    ports:
      - "6052:6052"
    volumes:
      - ./volumes/esphome/config:/config



